@startuml
title Диаграмма контейнеров MVP открытия депозитов

left to right direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

        

    Person(Клиент, "Клиент банка", "Подает заявки на депозит")

    System_Boundary(ИнтернетБанкСистема, "Интернет-банк") {
        Container(ИнтернетБанк, "Интернет-банк", "ASP.NET MVC 4.5 + MS SQL", "Онлайн-оформление депозитов")
        Container(Очереди, "Очереди сообщений", "Kafka", "Асинхронная интеграция систем")
    }

    System_Boundary(БанковскиеСистемы, "Автоматизированная Банковская система") {
        Container(АБС_Ядро, "Ядро АБС", "Delphi + Oracle", "Обработка транзакций, учет договоров")
        Container(АБС_Ставки, "Модуль ставок", "PL/SQL", "Расчет депозитных ставок")
        ContainerDb(АБС_БД, "БД АБС", "Oracle", "Хранение финансовых данных")
    }

    System_Boundary(Сервисы, "Сервисы") {
        Container(Сайт, "Сайт", "PHP + React.js", "Предоставление информации о депозитах и прием заявок")
        Container(КоллЦентр, "Система колл-центра", "Java Spring Boot + PostgreSQL", "Обработка входящих заявок")
        Container(СМСШлюз, "СМС-шлюз", "N/A", "Отправка SMS клиентам")
    }

    Rel(Клиент, Сайт, "Подает заявку", "HTTPS")
    Rel(Клиент, ИнтернетБанк, "Открывает депозит", "HTTPS")
    Rel(Сайт, КоллЦентр, "Передает заявку", "REST API")
    Rel(ИнтернетБанк, Очереди, "Отправляет заявку", "Kafka API")
    Rel(Очереди, АБС_Ядро, "Передает заявку", "Oracle AQ")
    Rel(АБС_Ядро, АБС_Ставки, "Запрашивает ставку", "PL/SQL")
    Rel(АБС_Ядро, АБС_БД, "Чтение/запись данных", "JDBC")
    Rel(АБС_Ядро, СМСШлюз, "Инициирует SMS", "SFTP")
    Rel(КоллЦентр, АБС_Ядро, "Синхронизирует данные", "SOAP API")

@enduml