@startuml
title Контекстная диаграмма MVP открытия депозитов

left to right direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(Клиент, "Клиент банка", "Подает заявки на депозит через сайт/интернет-банк")
    
    Container_Boundary(DepositSystem, "MVP Deposit System") {
    System(Сайт, "Сайт банка", "Отображает информацию о депозитах, принимает заявки")
    System(ИнтернетБанк, "Интернет-банк", "Прием заявок с подтверждением по SMS")
    System(КоллЦентр, "Система колл-центра", "Обработка заявок с сайта, звонки клиентам")
    System(АБС, "Автоматизированная банковская система", "Обработка заявок, расчет ставок, учет депозитов")
    System(БэкОфис, "Бэк-офис", "Ручная проверка и подтверждение заявок")
    System(СМСШлюз, "СМС-шлюз", "Отправка подтверждающих SMS")
    }
    Rel(Клиент, Сайт, "Подает заявку", "HTTPS")
    Rel(Клиент, ИнтернетБанк, "Открывает депозит", "HTTPS")
    Rel(Сайт, КоллЦентр, "Передает заявку", "REST API")
    Rel(ИнтернетБанк, АБС, "Отправляет заявку", "Асинхронные очереди (Kafka)")
    Rel(КоллЦентр, АБС, "Синхронизирует данные", "SOAP API")
    Rel(АБС, БэкОфис, "Передает на проверку", "Внутренний API")
    Rel(АБС, СМСШлюз, "Инициирует SMS", "SFTP")
    Rel(СМСШлюз, Клиент, "Отправляет SMS", "SMPP")
@enduml