@startuml
title Диаграмма контекста: Передача депозитных ставок в кол-центры

left to right direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml    

    Person(Клиент, "Клиент банка", "Звонит в кол-центр для уточнения условий депозита")
    Person(Оператор, "Оператор колл-центра", "Консультирует клиентов по ставкам")
    Person(Админ, "Администратор АБС", "Управляет ставками в банковской системе")

    System(АБС, "Автоматизированная банковская система", "Хранит и рассчитывает депозитные ставки")
    System(СервисСтавок, "Сервис экспорта ставок", "Преобразует данные в CSV, шифрует PGP")
    System(SFTP_Банк, "SFTP-сервер банка", "Хранит файлы для внутреннего колл-центра")
    System(SFTP_Партнер, "SFTP партнера", "Принимает файлы для внешнего колл-центра")
    System(CRM_Банк, "CRM банковского колл-центра", "Отображает ставки операторам")
    System(CRM_Партнер, "CRM партнерского колл-центра", "Внешняя система")

    Rel(Клиент, Оператор, "Запрос о ставках", "Телефонный звонок")
    Rel(Оператор, CRM_Банк, "Проверяет актуальные ставки", "Web-интерфейс")
    Rel(Админ, АБС, "Обновляет ставки", "Десктопный клиент")

    Rel(АБС, СервисСтавок, "Передает данные", "JDBC (каждые 15 мин)")
    Rel(СервисСтавок, SFTP_Банк, "Загружает файл", "SCP/PGP")
    Rel(СервисСтавок, SFTP_Партнер, "Отправляет файл", "SFTP/PGP")

    Rel(SFTP_Банк, CRM_Банк, "Синхронизирует данные", "Автоимпорт CSV")
    Rel(SFTP_Партнер, CRM_Партнер, "Предоставляет данные", "Ручная загрузка")
@enduml